# Generated by Django 3.1.3 on 2023-04-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scode', models.CharField(max_length=10)),
                ('scondition', models.TextField()),
                ('unitprice', models.IntegerField(default=0)),
                ('discountrate', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
            ],
        ),
    ]
