# Generated by Django 3.1.3 on 2023-04-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_seat_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
