# Generated by Django 3.1.3 on 2023-04-13 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0004_seat_modify_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seat',
            name='scondition',
            field=models.TextField(default='사용가능'),
        ),
    ]
